document.writeln("<div id=\'footer\' style=\'height:225px;\'>");
document.writeln("    <div class=\'content unselectable\'>");
document.writeln("        <div class=\'left\' style=\'\width:390px'>");
document.writeln("            <table>");
document.writeln("				<tr>");
document.writeln("					<td colspan=\'2\' height=\'10\'></td>");
document.writeln("				</tr>");
document.writeln("				<tr>");
document.writeln("					<td width=\'60\'><img src=\'/zsyy/web/imgs/logo_bottom.png\'></td>");
document.writeln("					<td>");
document.writeln("						<div><small>&copy; 2014 ������ѧ������ɽҽԺ ��Ȩ����</small></div>");
document.writeln("						<div style=\'height:5px\'></div>");
document.writeln("						<div><a href=\'http://newweb.zs-hospital.sh.cn:5691/rddb/index.htm\' target=\'_blank\'>�˴��������</a>��|��<a href=\'mailto:jss@zs-hospital.sh.cn\'>�з�ල����</a></div>");
document.writeln("					</td>");
document.writeln("					<td width=\'80\'><div style=\'width:80px;height:60px;margin-top:-20px;\'>");
document.write(unescape("%3Cspan id='_ideConac' %3E%3C/span%3E%3Cscript src='http://dcs.conac.cn/js/02/000/0000/60926060/CA020000000609260600003.js' type='text/javascript'%3E%3C/script%3E"));
document.writeln("					</div></td>");
document.writeln("				</tr>");
document.writeln("			</table>");
document.writeln("			<div style=\'height:10px\'></div>");
document.writeln("            <div><small>��ַ���Ϻ������������·180�š�|���ʱࣺ200032</small></div>");
document.writeln("            <div><small>�绰��021-64041990</small></div>");
document.writeln("			<div><small>������ѧ������ɽҽԺ������������</small></div>");
document.writeln("			<div><small><a href=\'http://www.miibeian.gov.cn\' target=\'_blank\'>��ICP��05026294��-10</a>��|������(��ҽ)������[2014]��10227�š�|��<a href=\'http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=31010402005005\' target=\'_blank\'><img src=\'/zsyy/imgs/ba.png\'>���������� 31010402005005��</a></small></div>");
document.writeln("        </div>");

document.writeln("		<div class=\'right\'>");
document.writeln("			<div>");
document.writeln("				<div><b>��������</b></div>");
document.writeln("				<div><a href=\'http://www.transplantation.com.cn/\' target=\'_blank\'>������ѧ������ֲ����</a></div>");

document.writeln("				<div><a href=\'http://www.91985.com/\' target=\'_blank\'>�Ϻ���ҽ��</a></div>");
document.writeln("				");
document.writeln("				<div><a href=\'http://www.shaphc.org/\' target=\'_blank\'>�Ϻ��й��������ٴ�����</a></div>");
document.writeln("				<div><a href=\'http://shmc.fudan.edu.cn/\' target=\'_blank\'>������ѧ�Ϻ�ҽѧԺ</a></div>");
document.writeln("			    <div><a href=\'http://www.fuccb.com\' target=\'_blank\'>�Ϻ����ٴ�������Ϣѧ�о���</a></div>");
document.writeln("			</div>");
document.writeln("			<div>");
document.writeln("				<div><b>&nbsp;</b></div>");
document.writeln("				<div><a href=\'http://www.c-jcm.com/zglcyx/ch/index.aspx/\' target=\'_blank\'>�й��ٴ�ҽѧ��־��</a></div>");
document.writeln("				<div><a href=\'http://www.redcross-sha.org/\' target=\'_blank\'>�Ϻ��к�ʮ�ֻ�</a></div>");
document.writeln("				<div><a href=\'http://xhredcross.xh.sh.cn/\' target=\'_blank\'>�������ʮ�ֻ�</a></div>");
document.writeln("				<div><a href=\'http://www.zsxmhospital.com/\' target=\'_blank\'>������ɽ����ҽԺ</a></div>");
document.writeln("			</div>");
document.writeln("		</div>");
document.writeln("    </div>");
document.writeln("</div>");