
var _hmt = _hmt || [];
(function() {
  var hm = document.createElement("script");
  hm.src = "https://hm.baidu.com/hm.js?6fee8e5537fbb63e5addd3f3228abda7 ";
  var s = document.getElementsByTagName("script")[0]; 
  s.parentNode.insertBefore(hm, s);
})();


var formValue = {
	cd:function(ele){
		if(ele.value==ele.defaultValue){ele.value = "";}
	},
	rd:function(ele){
		if(ele.value.replace(/\s+/g,'')==""){ele.value = ele.defaultValue;}
	}
}

document.writeln("    <div id=\'top\'>");
document.writeln("        <div class=\'content\'>");
document.writeln("  		<div id=\'logo\'></div>");

document.writeln("            <div class=\'right\'>");
document.writeln("                <div class=\'links\'>");
document.writeln("                　<a href=\'http://newweb.zs-hospital.sh.cn:5691/index1.htm\' target=\'_blank\'>旧版网站</a>　|　<a href=\'/zsyy/n15/index.html\' target=\'_blank\'>English</a></div>");
document.writeln("                <div id=\'search\'>");
document.writeln("<form method=\'post\' action=\'http://ecms.eastday.com/zsyy_serach/Search.aspx\' id=\'ctl00\'>");
document.writeln("                    <input id=\'txtKey\' name=\'q\' class=\'input\' type=\'text\' value=\'找医生 / 找科室 / 找病症 / 找信息\'  maxlength=\'15\' onfocus=\'formValue.cd(this)\' onblur=\'formValue.rd(this)\'>");
document.writeln("					<input class=\'go\' type=\'submit\' value=\'\'>");
document.writeln("</form>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("");
document.writeln("    ");
document.writeln("<div id=\'menu\'>");
document.writeln("	<div id=\'nav\' role=\'navigation\'>");
document.writeln("	    <ul>");
document.writeln("            ");
document.writeln("              <li >");
document.writeln("                <a href=\'/zsyy/n33/index.html\' >网站首页</a>");
document.writeln("              </li>  ");
document.writeln("            ");
document.writeln("              <li class=\'has-sub\'>");
document.writeln("                <a href=\'/zsyy/n33/n34/index.html\' >就医入口</a>");
document.writeln("                <ul>");
document.writeln("                        <li>");
document.writeln("                        <a href=\'/zsyy/n33/n34/n40/index.html\' >预约挂号</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                        <a href=\'/zsyy/n33/n34/n41/index.html\' >健康管理中心</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                        <a href=\'https://oa.zs-hospital.sh.cn/medinswebcheck/Default.aspx\' target=\'_blank\'>医疗文书校验服务</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                        <a href=\'http://newweb.zs-hospital.sh.cn:5691/dyxx.htm\' >导医信息</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                        <a href=\'http://newweb.zs-hospital.sh.cn:5691/menzhen/zjmz.htm\' target=\'_blank\'>专家门诊</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                        <a href=\'http://newweb.zs-hospital.sh.cn:5691/menzhen/gkmz.htm\' target=\'_blank\'>普通及专病门诊 </a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                        <a href=\'http://newweb.zs-hospital.sh.cn:5691/yuyue/yuyue.htm\' target=\'_blank\'>门诊出停诊信息查询 </a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                        <a href=\'/zsyy/n33/n34/n47/index.html\' >交通指南</a>");
document.writeln("                        </li>");
document.writeln("                </ul>");
document.writeln("              </li>  ");
document.writeln("            ");
document.writeln("              <li class=\'has-sub\'>");
document.writeln("                <a href=\'#\' >学科及专家</a>");
document.writeln("                <ul>");
document.writeln("                        <li>");
document.writeln("                        <a href=\'/zsyy/n33/n35/n48/index.html\' >学科及专家介绍</a>");
document.writeln("                        </li>");
document.writeln("                </ul>");
document.writeln("              </li>  ");
document.writeln("            ");
document.writeln("              <li class=\'has-sub\'>");
document.writeln("                <a href=\'/zsyy/n33/n36/index.html\' >科学研究</a>");
document.writeln("                <ul>");
document.writeln("                        <li>");
document.writeln("                        <a href=\'/zsyy/n33/n36/n49/index.html\' >科研处</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                        <a href=\'/zsyy/n33/n36/n50/index.html\' >科研信息</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                        <a href=\'/zsyy/n33/n36/n51/index.html\' >临床医学研究院</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                        <a href=\'http://www.c-jcm.com/zglcyx/ch/index.aspx\' target=\'_blank\'>临床医学杂志编辑部</a>");
document.writeln("                        </li>");
document.writeln("                </ul>");
document.writeln("              </li>  ");
document.writeln("            ");
document.writeln("              <li class=\'has-sub\'>");
document.writeln("                <a href=\'/zsyy/n33/n37/index.html\' target=\'_blank\'>医学教育</a>");
document.writeln("                <ul>");
document.writeln("                        <li>");
document.writeln("                        <a href=\'/zsyy/n33/n37/index.html\' target=\'_blank\'>教育处首页</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                        <a href=\'/zsyy/n33/n37/n525/index.html\' target=\'_blank\'>本科生教育</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                        <a href=\'/zsyy/n33/n37/n526/index.html\' target=\'_blank\'>研究生教育</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                        <a href=\'/zsyy/n33/n37/n527/index.html\' target=\'_blank\'>住院医生培养</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                        <a href=\'/zsyy/n33/n37/n528/index.html\' target=\'_blank\'>专科医生培养</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                        <a href=\'/zsyy/n33/n37/n529/index.html\' target=\'_blank\'>进修教育</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                        <a href=\'/zsyy/n33/n37/n530/index.html\' target=\'_blank\'>继续医学教育</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                        <a href=\'/zsyy/n33/n37/n531/index.html\' target=\'_blank\'>远程医学</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                        <a href=\'/zsyy/n33/n37/n702/index.html\' target=\'_blank\'>教学学术会议</a>");
document.writeln("                        </li>");
document.writeln("                </ul>");
document.writeln("              </li>  ");
document.writeln("            ");
document.writeln("              <li >");
document.writeln("                <a href=\'/zsyy/n33/n38/index.html\' >人才招聘</a>");
document.writeln("              </li>  ");
document.writeln("            ");
document.writeln("              <li class=\'has-sub\'>");
document.writeln("                <a href=\'/zsyy/n33/n39/index.html\' >中山信息</a>");
document.writeln("                <ul>");
document.writeln("                        <li>");
document.writeln("                        <a href=\'https://oa.zs-hospital.sh.cn/portal\' >办公管理平台</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                        <a href=\'http://woa.zs-hospital.sh.cn:8680\' >新OA系统</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                        <a href=\'/zsyy/n33/n39/n52/index.html\' target=\'_blank\'>中山医院报</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                        <a href=\'/zsyy/n33/n39/n53/index.html\' >院史考据</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                        <a href=\'http://zhushou.360.cn/detail/index/soft_id/2635919\' >中山手机App(安卓版)</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                        <a href=\'/zsyy/n33/n39/n55/index.html\' >中山手机App下载</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                        <a href=\'/zsyy/n33/n39/n56/index.html\' >媒体视点</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                        <a href=\'/zsyy/n33/n39/n694/u1ai3497.html\' >中山故事</a>");
document.writeln("                        </li>");
document.writeln("                </ul>");
document.writeln("              </li>  ");
document.writeln("	    </ul>");
document.writeln("	</div>");
document.writeln("</div>");